drivers: misc/mtk: typec/tcpc_ares: Discard unused variable local_index
../drivers/misc/mediatek/typec/tcpc_ares/pd_dpm_alt_mode_dp.c:352:6: error: variable 'local_index' set but not used [-Werror,-Wunused-but-set-variable]
        int local_index = -1, remote_index = -1;
            ^
1 error generated.